# Github Crowdin Action
# https://github.com/marketplace/actions/crowdin-action

# For more detailed descriptions of these options, 'with'.
# https://github.com/crowdin/github-action/blob/master/action.yml

# Crowdin configuration file, crowdin.yml
# https://developer.crowdin.com/configuration-file/

name: crowdin-action

on: 
  workflow_dispatch:
    inputs:
      upload_translations:
        description: 'Upload translations to Crowdin?'
        required: false
        default: 'false'
        type: boolean

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: crowdin action
      uses: crowdin/github-action@v2
      with:
        # --------------------------------------------------------------------------------------
        #  Upload options: https://github.com/marketplace/actions/crowdin-action#upload-options
        # --------------------------------------------------------------------------------------
        # upload_sources: false  # default: true
        upload_translations: ${{ github.event.inputs.upload_translations }} # default: false
        upload_language: 'ja'
        # auto_approve_imported: true # default: false
        # import_eq_suggestions: true # default: false
        # upload_sources_args: --no-auto-update label=web
        # upload_translations_args: --translate-hidden
        
        # ------------------------------------------------------------------------------------------
        #  Download options: https://github.com/marketplace/actions/crowdin-action#download-options
        # ------------------------------------------------------------------------------------------
        # download_sources: true # default: false
        download_translations: true # default: false
        # download_bundle: 1
        download_language: 'ja'
        # skip_untranslated_strings: true # default: false
        # skip_untranslated_files: true # default: false
        # export_only_approved: true # default: false
        # download_sources_args: --reviewed
        # download_translations_args: --all --skip-untranslated-strings

        # -----------------------------------------------------------------------------------------------------------------
        # Git and Pull Request options: https://github.com/marketplace/actions/crowdin-action#git-and-pull-request-options
        # -----------------------------------------------------------------------------------------------------------------
        # push_translations: false # default: true
        # push_sources: false # default: true
        # localization_branch_name: l10n_crowdin_action
        # commit_message: New Crowdin translations by GitHub Action
        # create_pull_request: false # default: true
        # pull_request_title: New Crowdin translations by GitHub Action
        # pull_request_body: New Crowdin pull request with translations
        # pull_request_labels: localization, l10n
        # pull_request_assignees: crowdin-bot
        # pull_request_reviewers: user-reviewer
        # pull_request_team_reviewers: team-reviewer
        # pull_request_base_branch_name: main
        # skip_ref_checkout: true # default: false

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
